### ISSUE TITLE
RangeError(index) issue, suspected for headers and rows

### ISSUE THREAD

**Issue by i-maple** [herbertamukhuma/scrollable_table_view#19]

**Comment by i-maple** [comment]
Here is the error : 
════════ Exception caught by widgets library ═══════════════════════════════════
The following RangeError was thrown building TableViewRow(dirty):
RangeError (index): Invalid value: Not in inclusive range 0..22: 23

The relevant error-causing widget was:
    TableViewRow TableViewRow:file:///C:/school_asset_management_system/lib/ui/screens/home_screen_views/report_view.dart:34:32

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      TableViewRow.build.<anonymous closure> (package:scrollable_table_view/src/scrollable_table_view.dart:401:33)
#2      Utils.map (package:scrollable_table_view/src/utils.dart:8:30)
#3      TableViewRow.build (package:scrollable_table_view/src/scrollable_table_view.dart:396:31)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5541:49)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (68 frames)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#80     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#81     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (120 frames)
#201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#202    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#203    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (4 frames)
#207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#209    _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:132:18)
#210    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
#211    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:150:12)
#212    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
#213    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
#214    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
#215    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
#216    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:308:5)
#217    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#218    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#219    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#220    RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:868:45)
#221    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#222    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#223    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#224    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:310:14)
#225    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#226    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#227    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#228    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#229    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#230    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#231    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#232    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#233    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#234    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#235    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#236    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#237    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#238    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#239    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#240    _invoke (dart:ui/hooks.dart:312:13)
#241    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#242    _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..22: 23
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

**Comment by herbertamukhuma** [comment]
Hello, kindly provide a code sample that produces the error above
